Repository UnUniFi/web-apps, pull requests merged in 2022-06, with the labels that each got.

#200 feat: refactor and enable keplr
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/keplr/keplr.application.service.ts
  projects/portal/src/app/models/wallets/keplr/keplr.infrastructure.service.ts
  projects/portal/src/app/models/wallets/keplr/keplr.service.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/views/dialogs/wallets/keplr/keplr-import-wallet-dialog/keplr-import-wallet-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/keplr/keplr-import-wallet-dialog/keplr-import-wallet-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/keplr/keplr-import-wallet-dialog/keplr-import-wallet-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/keplr/keplr-import-wallet-dialog/keplr-import-wallet-dialog.module.ts
Labels: enhancement

#195 hotfix: suport to import from mnemonic with manual typing input
  projects/portal/src/app/models/cosmos/bank.application.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/keys/key.service.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/pages/keys/create/create.component.ts
  projects/portal/src/app/utils/key.ts
  projects/portal/src/app/utils/validation.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
Labels: bug, enhancement

#204 hotfix: suport to import from mnemonic with manual typing input
  projects/portal/src/app/models/cosmos/bank.application.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/keys/key.service.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/pages/keys/create/create.component.ts
  projects/portal/src/app/utils/key.ts
  projects/portal/src/app/utils/validation.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
Labels: bug, enhancement

#196 feat: withdraw delegator reward
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/cosmos/distribution.application.service.ts
  projects/portal/src/app/models/cosmos/distribution.service.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.css
  projects/portal/src/app/pages/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.css
  projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/withdraw-delegator-reward-form-dialog/withdraw-delegator-reward-form-dialog.module.ts
Labels: enhancement

#198 hotfix: support to import wallet with privatekey
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/pages/keys/create/create.component.ts
  projects/portal/src/app/utils/key.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
Labels: enhancement

#211 hotfix: support to import wallet with privatekey
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/pages/keys/create/create.component.ts
  projects/portal/src/app/utils/key.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
Labels: enhancement

#194 feat: metamask support
  package-lock.json
  package.json
  projects/explorer/src/app/pages/accounts/account/account.component.ts
  projects/explorer/src/app/views/accounts/account/account.component.ts
  projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
  projects/explorer/src/app/views/proposals/proposals.component.ts
  projects/explorer/src/app/views/txs/tx/tx.component.ts
  projects/explorer/src/assets/config.js
  projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
  projects/portal/src/app/models/cdps/cdp.infrastructure.service.ts
  projects/portal/src/app/models/cosmos/bank.application.service.ts
  projects/portal/src/app/models/cosmos/bank.service.ts
  projects/portal/src/app/models/cosmos/gentx.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.model.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/keys/key.infrastructure.service.ts
  projects/portal/src/app/models/keys/key.model.ts
  projects/portal/src/app/models/wallets/metamask/metamask.infrastructure.service.ts
  projects/portal/src/app/models/wallets/metamask/metamask.service.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/models/wallets/wallet.model.ts
  projects/portal/src/app/pages/accounts/account/account.component.ts
  projects/portal/src/app/pages/auction/auctions/auction/auction.component.ts
  projects/portal/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
  projects/portal/src/app/pages/auction/auctions/auctions.component.ts
  projects/portal/src/app/pages/balance/balance.component.ts
  projects/portal/src/app/utils/key.ts
  projects/portal/src/app/views/accounts/account/account.component.ts
  projects/portal/src/app/views/cosmos/staking/validators/validator/validator.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.ts
  projects/portal/src/app/views/txs/tx/tx.component.ts
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
  projects/portal/src/app/views/vote/proposals/proposals.component.ts
  projects/portal/src/assets/config.js
  projects/portal/src/assets/metamask-logo.svg
  projects/portal/src/polyfills.ts
  tsconfig.json
Labels: enhancement

#214 feat: new alpha-test network related implementation
  projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/explorer/src/assets/config.js
  projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/portal/src/app/models/faucets/faucet.application.service.ts
  projects/portal/src/app/models/faucets/faucet.infrastructure.service.ts
  projects/portal/src/app/models/faucets/faucet.model.ts
  projects/portal/src/app/models/faucets/faucet.service.ts
  projects/portal/src/assets/config.js
Labels: enhancement

#215 fix: config.js on alpha-test to recover chainName
  projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
Labels: bug

#216 fix: config.js to recover chainName for debug
  projects/explorer/src/assets/config.js
  projects/portal/src/assets/config.js
Labels: bug

#221 docs: readme of web apps
  README.md
  projects/explorer/README.md
  projects/landing-page-html/README.md
  projects/portal/README.md
Labels: documentation

#224 fix: recover unintentional removal of marketplace angular json
  angular.json
Labels: bug
