Repository UnUniFi/web-apps, pull requests merged in 2022-04, with the labels that each got.

#62 feat: fix create validator
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.model.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/pages/cosmos/staking/staking-routing.module.ts
  projects/portal/src/app/pages/cosmos/staking/staking.module.ts
  projects/portal/src/app/pages/staking/create-validator/create-validator.component.css
  projects/portal/src/app/pages/staking/create-validator/create-validator.component.html
  projects/portal/src/app/pages/staking/create-validator/create-validator.component.ts
  projects/portal/src/app/pages/staking/staking-routing.module.ts
  projects/portal/src/app/pages/staking/staking.module.ts
  projects/portal/src/app/views/cosmos/staking/create-validator/create-validator.component.html
  projects/portal/src/app/views/material.module.ts
  projects/portal/src/app/views/staking/create-validator/create-validator.component.css
  projects/portal/src/app/views/staking/create-validator/create-validator.component.html
  projects/portal/src/app/views/staking/create-validator/create-validator.component.ts
  projects/portal/src/app/views/staking/create-validator/create-validator.module.ts
  projects/portal/src/app/views/staking/staking.module.ts
Labels: enhancement

#68 fix: create validator commission rate unit
  projects/portal/src/app/models/cosmos/staking.service.ts
Labels: bug

#65 fix: password saving feature and change backup file's extension from json to text
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-mnemonic-and-private-key-wizard-dialog/ununifi-backup-mnemonic-and-private-key-wizard-dialog.component.ts
Labels: bug

#73 feat: portal home balances
  package.json
  projects/explorer/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
  projects/explorer/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/explorer/src/assets/config.js
  projects/portal/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/models/faucets/faucet.application.service.ts
  projects/portal/src/app/models/faucets/faucet.infrastructure.service.ts
  projects/portal/src/app/models/faucets/faucet.model.ts
  projects/portal/src/app/models/faucets/faucet.service.ts
  projects/portal/src/app/pages/balance/balance-routing.module.ts
  projects/portal/src/app/pages/balance/balance.component.css
  projects/portal/src/app/pages/balance/balance.component.html
  projects/portal/src/app/pages/balance/balance.component.ts
  projects/portal/src/app/pages/balance/balance.module.ts
  projects/portal/src/app/utils/converter.ts
  projects/portal/src/app/views/app.component.html
  projects/portal/src/app/views/balance/balance.component.css
  projects/portal/src/app/views/balance/balance.component.html
  projects/portal/src/app/views/balance/balance.component.ts
  projects/portal/src/app/views/balance/balance.module.ts
  projects/portal/src/app/views/dialogs/wallets/connect-wallet-completed-dialog/connect-wallet-completed-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/connect-wallet-start-dialog/connect-wallet-start-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-mnemonic-and-private-key-wizard-dialog/ununifi-backup-mnemonic-and-private-key-wizard-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-key-form-dialog/ununifi-key-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-wallet-dialog/ununifi-select-wallet-dialog.component.html
  projects/portal/src/assets/config.js
Labels: bug, enhancement

#77 feat: cd beta test
  .firebaserc
  .github/workflows/cd-firebase-ununifi-beta-test.yml
  firebase.json
  package.json
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/README.md
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/docker-compose.yml
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/full/config.js
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/full/deploy.sh
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/light/config.js
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/light/deploy.sh
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/standard/config.js
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/standard/deploy.sh
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/README.md
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/docker-compose.yml
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/full/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/full/deploy.sh
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/light/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/light/deploy.sh
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/standard/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/standard/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/README.md
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/docker-compose.yml
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/full/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/full/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/light/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/light/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/standard/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/standard/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-beta-test/README.md
  projects/portal/editions/ununifi/launch/ununifi-beta-test/docker-compose.yml
  projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/full/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/full/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-beta-test/light/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/light/deploy.sh
  projects/portal/editions/ununifi/launch/ununifi-beta-test/standard/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/standard/deploy.sh
Labels: enhancement

#75 feat: accounts create simple
  projects/portal/src/app/pages/accounts/accounts-routing.module.ts
  projects/portal/src/app/pages/accounts/create/create-routing.module.ts
  projects/portal/src/app/pages/accounts/create/create.module.ts
  projects/portal/src/app/pages/accounts/create/simple/simple-routing.module.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.component.css
  projects/portal/src/app/pages/accounts/create/simple/simple.component.html
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/pages/accounts/create/simple/simple.module.ts
  projects/portal/src/app/views/accounts/create/simple/simple.component.css
  projects/portal/src/app/views/accounts/create/simple/simple.component.html
  projects/portal/src/app/views/accounts/create/simple/simple.component.ts
  projects/portal/src/app/views/accounts/create/simple/simple.module.ts
Labels: enhancement

#82 fix: disable faucet on beta test
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
Labels: bug

#83 fix: disable faucet on beta test
  projects/explorer/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/explorer/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
Labels: bug

#84 Feature/account detail page
  projects/explorer/src/app/pages/accounts/account/account.component.html
  projects/explorer/src/app/pages/accounts/account/bank/bank.component.css
  projects/explorer/src/app/pages/accounts/account/bank/bank.component.html
  projects/explorer/src/app/pages/accounts/account/bank/bank.component.ts
  projects/explorer/src/app/pages/accounts/account/distribution/distribution.component.css
  projects/explorer/src/app/pages/accounts/account/distribution/distribution.component.html
  projects/explorer/src/app/pages/accounts/account/distribution/distribution.component.ts
  projects/explorer/src/app/pages/accounts/account/staking/staking.component.css
  projects/explorer/src/app/pages/accounts/account/staking/staking.component.html
  projects/explorer/src/app/pages/accounts/account/staking/staking.component.ts
  projects/explorer/src/app/pages/accounts/accounts.module.ts
  projects/explorer/src/app/views/accounts/account/account.component.html
  projects/explorer/src/app/views/accounts/account/account.component.ts
  projects/explorer/src/app/views/accounts/account/bank/bank.component.css
  projects/explorer/src/app/views/accounts/account/bank/bank.component.html
  projects/explorer/src/app/views/accounts/account/bank/bank.component.ts
  projects/explorer/src/app/views/accounts/account/bank/bank.module.ts
  projects/explorer/src/app/views/accounts/account/distribution/distribution.component.css
  projects/explorer/src/app/views/accounts/account/distribution/distribution.component.html
  projects/explorer/src/app/views/accounts/account/distribution/distribution.component.ts
  projects/explorer/src/app/views/accounts/account/distribution/distribution.module.ts
  projects/explorer/src/app/views/accounts/account/staking/staking.component.css
  projects/explorer/src/app/views/accounts/account/staking/staking.component.html
  projects/explorer/src/app/views/accounts/account/staking/staking.component.ts
  projects/explorer/src/app/views/accounts/account/staking/staking.module.ts
  projects/explorer/src/app/views/accounts/account/txs/txs.component.html
Labels: enhancement

#90 hotfix: disable cd on release published
  .github/workflows/cd-firebase-ununifi-8-private-test.yml
  .github/workflows/cd-firebase-ununifi-alpha-test.yml
  .github/workflows/cd-firebase-ununifi.yml
Labels: enhancement

#92 Hotfix/disable faucet
  projects/portal/src/app/app.component.ts
  projects/portal/src/assets/config.js
Labels: bug

#93 hotfix: minimum gas price readonly
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/staking/create-validator/create-validator.component.html
Labels: bug

#95 hotfix: minimum gas price readonly
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/staking/create-validator/create-validator.component.html
Labels: bug

#97 hotfix: disable monitor on beta test
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-beta-test/firebase-hosting/config.js
Labels: bug

#74 feat: proposal list page, proposal details page, deposit form dialog and voting form dialog
  projects/explorer/src/app/pages/proposals/proposal/proposal.component.html
  projects/explorer/src/app/pages/proposals/proposal/proposal.component.ts
  projects/explorer/src/app/views/proposals/proposal/proposal.component.html
  projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/cosmos/gov.application.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.css
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.module.ts
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.css
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.module.ts
  projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.html
  projects/portal/src/app/pages/vote/proposals/proposal/proposal.component.ts
  projects/portal/src/app/pages/vote/proposals/proposals.component.html
  projects/portal/src/app/pages/vote/proposals/proposals.component.ts
  projects/portal/src/app/pages/vote/vote-routing.module.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.css
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.css
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.module.ts
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
  projects/portal/src/app/views/vote/proposals/proposal/proposal.module.ts
  projects/portal/src/app/views/vote/proposals/proposals.component.html
  projects/portal/src/app/views/vote/proposals/proposals.component.ts
Labels: enhancement

#101 fix: if empty validator website, disable website link
  projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
Labels: bug

#106 chore: proposal param
  projects/explorer/src/app/views/proposals/proposal/proposal.component.html
  projects/explorer/src/app/views/proposals/proposal/proposal.component.ts
  projects/explorer/src/app/views/proposals/proposals.component.html
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.ts
  projects/portal/src/app/views/vote/proposals/proposals.component.html
Labels: enhancement

#107 feat: add users delegations info to delegate page
  projects/portal/src/app/pages/delegate/validators/validators.component.html
  projects/portal/src/app/pages/delegate/validators/validators.component.ts
  projects/portal/src/app/views/delegate/validators/validators.component.html
  projects/portal/src/app/views/delegate/validators/validators.component.ts
Labels: enhancement

#108 feat: add users delegations info to delegate page
  projects/portal/src/app/pages/delegate/validators/validators.component.html
  projects/portal/src/app/pages/delegate/validators/validators.component.ts
  projects/portal/src/app/views/delegate/validators/validators.component.html
  projects/portal/src/app/views/delegate/validators/validators.component.ts
Labels: enhancement

#104 fix: delegate dialog to disable redelegate same validator and warn on delegate to an inactive validator
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.css
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.module.ts
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
Labels: bug, enhancement

#105 fix: delegate dialog to disable redelegate same validator and warn on delegate to an inactive validator
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.css
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/invalid-validator-confirm-dialog/inactive-validator-confirm-dialog.module.ts
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
Labels: bug, enhancement

#110 feat: add buttons to account create simple page
  projects/portal/src/app/pages/accounts/create/simple/simple.component.html
  projects/portal/src/app/pages/accounts/create/simple/simple.component.ts
  projects/portal/src/app/views/accounts/create/simple/simple.component.html
  projects/portal/src/app/views/accounts/create/simple/simple.component.ts
  projects/portal/src/app/views/accounts/create/simple/simple.module.ts
Labels: enhancement

#113 feat: change gas settings form to show gas ratio with toggle button ui and hide gas price
  projects/portal/src/app/models/auctions/auction.application.service.ts
  projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
  projects/portal/src/app/models/auctions/auction.service.ts
  projects/portal/src/app/models/cdps/cdp.application.service.ts
  projects/portal/src/app/models/cdps/cdp.infrastructure.service.ts
  projects/portal/src/app/models/cdps/cdp.service.ts
  projects/portal/src/app/models/cosmos/bank.application.service.ts
  projects/portal/src/app/models/cosmos/bank.service.ts
  projects/portal/src/app/models/cosmos/gov.application.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/tx-common/tx-common.application.service.ts
  projects/portal/src/app/models/tx-common/tx-common.infrastructure.service.ts
  projects/portal/src/app/models/tx-common/tx-common.model.ts
  projects/portal/src/app/models/tx-common/tx-common.service.ts
  projects/portal/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
  projects/portal/src/app/pages/cosmos/bank/send/send.component.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/clear/clear.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/deposit/deposit.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/issue/issue.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/withdraw/withdraw.component.ts
  projects/portal/src/app/pages/mint/cdps/create/create.component.ts
  projects/portal/src/app/pages/staking/create-validator/create-validator.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
Labels: enhancement

#114 release v1.0.0-beta.3
  projects/portal/src/app/models/auctions/auction.application.service.ts
  projects/portal/src/app/models/auctions/auction.infrastructure.service.ts
  projects/portal/src/app/models/auctions/auction.service.ts
  projects/portal/src/app/models/cdps/cdp.application.service.ts
  projects/portal/src/app/models/cdps/cdp.infrastructure.service.ts
  projects/portal/src/app/models/cdps/cdp.service.ts
  projects/portal/src/app/models/cosmos/bank.application.service.ts
  projects/portal/src/app/models/cosmos/bank.service.ts
  projects/portal/src/app/models/cosmos/gov.application.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/tx-common/tx-common.application.service.ts
  projects/portal/src/app/models/tx-common/tx-common.infrastructure.service.ts
  projects/portal/src/app/models/tx-common/tx-common.model.ts
  projects/portal/src/app/models/tx-common/tx-common.service.ts
  projects/portal/src/app/pages/auction/auctions/auction/place-bid/place-bid.component.ts
  projects/portal/src/app/pages/cosmos/bank/send/send.component.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/deposit-form-dialog/deposit-form-dialog.component.ts
  projects/portal/src/app/pages/dialogs/vote/vote-form-dialog/vote-form-dialog.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/clear/clear.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/deposit/deposit.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/issue/issue.component.ts
  projects/portal/src/app/pages/mint/cdps/cdp/withdraw/withdraw.component.ts
  projects/portal/src/app/pages/mint/cdps/create/create.component.ts
  projects/portal/src/app/pages/staking/create-validator/create-validator.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-menu-dialog/delegate-menu-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
  projects/portal/src/app/views/vote/proposals/proposal/proposal.component.html
Labels: enhancement

#116 fix: Txs not showing in Dashboard when no txs
  projects/explorer/src/app/pages/dashboard/dashboard.component.html
  projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
  projects/explorer/src/app/views/dashboard/dashboard.component.html
Labels: bug

#117 fix: Txs not showing in Dashboard when no txs
  projects/explorer/src/app/pages/dashboard/dashboard.component.html
  projects/explorer/src/app/pages/dashboard/txs/txs.component.ts
  projects/explorer/src/app/views/dashboard/dashboard.component.html
Labels: bug

#66 feat: block details page
  projects/explorer/src/app/pages/blocks/block/block.component.html
  projects/explorer/src/app/pages/blocks/block/block.component.ts
  projects/explorer/src/app/views/blocks/block/block.component.html
  projects/explorer/src/app/views/blocks/block/block.component.ts
Labels: enhancement

#99 feat: set accordion to tx-detail-page
  projects/explorer/src/app/pages/txs/tx/tx.component.html
  projects/explorer/src/app/pages/txs/tx/tx.component.ts
  projects/explorer/src/app/views/material.module.ts
  projects/explorer/src/app/views/txs/tx/tx.component.html
  projects/explorer/src/app/views/txs/tx/tx.component.ts
Labels: enhancement

#125 fix: prevent overwrite with same wallet id
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-mnemonic-form-dialog/ununifi-import-wallet-with-mnemonic-form-dialog.component.ts
Labels: bug, enhancement

#87 feat: create validator simple
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/pages/staking/create-validator-simple/create-validator-simple.component.css
  projects/portal/src/app/pages/staking/create-validator-simple/create-validator-simple.component.html
  projects/portal/src/app/pages/staking/create-validator-simple/create-validator-simple.component.ts
  projects/portal/src/app/pages/staking/staking-routing.module.ts
  projects/portal/src/app/pages/staking/staking.module.ts
  projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.component.css
  projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.component.html
  projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.component.ts
  projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.module.ts
Labels: enhancement
