Repository UnUniFi/web-apps, pull requests merged in 2022-05, with the labels that each got.

#140 feat: import wallet with private key
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
Labels: enhancement

#135 fix: portal create validator simple title
  projects/portal/src/app/views/staking/create-validator-simple/create-validator-simple.component.html
Labels: enhancement

#136 fix: portal home validator link
  projects/portal/src/app/views/balance/balance.component.html
Labels: bug

#137 fix: explorer dashboard inflation margin bottom
  projects/explorer/src/app/views/dashboard/dashboard.component.html
Labels: bug

#148 fix: search bar redirect url
  projects/portal/src/app/app.component.ts
Labels: enhancement

#154 fix: revert #140 (import from privkey) to fix issue #150
  package.json
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/models/wallets/wallet.application.service.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-backup-private-key-wizard-dialog/ununifi-backup-private-key-wizard-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.css
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.html
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-import-wallet-with-private-key-form-dialog/ununifi-import-wallet-with-private-key-form-dialog.module.ts
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-select-create-import-dialog/ununifi-select-create-import-dialog.component.ts
Labels: bug

#156 feat: sign delegate with ununifi & keplr
  package-lock.json
  package.json
  projects/portal/editions/ununifi/launch/ununifi-8-private-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-9-beta-test-v1/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi-alpha-test/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
  projects/portal/src/app/models/config.service.ts
  projects/portal/src/app/models/cosmos/keplr/keplr-staking.application.service.ts
  projects/portal/src/app/models/cosmos/keplr/keplr-staking.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/keplr/keplr.application.service.ts
  projects/portal/src/app/models/keplr/keplr.service.ts
  projects/portal/src/app/pages/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/assets/config.js
Labels: enhancement

#157 fix: delete some img when window size is for mobile
  projects/landing-page/src/app/views/home/home.component.css
  projects/landing-page/src/app/views/home/home.component.html
Labels: bug

#164 feat: implement slashing unjail and fix to support tx fee both 0 and not 0
  projects/portal/src/app/app-routing.module.ts
  projects/portal/src/app/models/cosmos/slashing.application.service.ts
  projects/portal/src/app/models/cosmos/slashing.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/pages/slashing/slashing-routing.module.ts
  projects/portal/src/app/pages/slashing/slashing.module.ts
  projects/portal/src/app/pages/slashing/unjail-simple/unjail-simple.component.css
  projects/portal/src/app/pages/slashing/unjail-simple/unjail-simple.component.html
  projects/portal/src/app/pages/slashing/unjail-simple/unjail-simple.component.ts
  projects/portal/src/app/pages/slashing/unjail/unjail.component.css
  projects/portal/src/app/pages/slashing/unjail/unjail.component.html
  projects/portal/src/app/pages/slashing/unjail/unjail.component.ts
  projects/portal/src/app/views/slashing/slashing.module.ts
  projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.component.css
  projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.component.html
  projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.component.ts
  projects/portal/src/app/views/slashing/unjail-simple/unjail-simple.module.ts
  projects/portal/src/app/views/slashing/unjail/unjail.component.css
  projects/portal/src/app/views/slashing/unjail/unjail.component.html
  projects/portal/src/app/views/slashing/unjail/unjail.component.ts
  projects/portal/src/app/views/slashing/unjail/unjail.module.ts
Labels: bug, enhancement

#170 feat: ununifi-test-v2 config
  projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
Labels: enhancement

#166 feat: handle create-validator for multiple validators in the portal app
  package-lock.json
  package.json
  projects/portal/src/app/app.module.ts
  projects/portal/src/app/graphql.module.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/pages/staking/create-validator-multiple/create-validator-multiple.component.css
  projects/portal/src/app/pages/staking/create-validator-multiple/create-validator-multiple.component.html
  projects/portal/src/app/pages/staking/create-validator-multiple/create-validator-multiple.component.ts
  projects/portal/src/app/pages/staking/staking-routing.module.ts
  projects/portal/src/app/pages/staking/staking.module.ts
  projects/portal/src/app/views/material.module.ts
  projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.component.css
  projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.component.html
  projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.component.ts
  projects/portal/src/app/views/staking/create-validator-multiple/create-validator-multiple.module.ts
  projects/portal/src/app/views/staking/create-validator-multiple/validator-dialog.css
  projects/portal/src/app/views/staking/create-validator-multiple/validator-dialog.html
  tsconfig.json
Labels: enhancement

#180 hotfix: change default to 0 fee and change default gas limit from 200000 to 1000000
  projects/explorer/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
Labels: bug, enhancement

#181 hotfix: change default to 0 fee and change default gas limit from 200000 to 1000000
  projects/explorer/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/models/cosmos/gov.service.ts
  projects/portal/src/app/models/cosmos/staking.application.service.ts
  projects/portal/src/app/models/cosmos/staking.service.ts
  projects/portal/src/app/models/cosmos/tx-common.service.ts
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/delegate-form-dialog/delegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/redelegate-form-dialog/redelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.html
  projects/portal/src/app/views/dialogs/delegate/undelegate-form-dialog/undelegate-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/deposit/deposit-form-dialog.component.ts
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.html
  projects/portal/src/app/views/dialogs/vote/vote/vote-form-dialog.component.ts
Labels: bug, enhancement

#182 fix: add BLOG button (link to medium)
  projects/landing-page/src/app/views/home/home.component.html
Labels: enhancement

#183 fix: add BLOG button (link to medium)
  projects/landing-page/src/app/views/home/home.component.html
Labels: enhancement

#185 fix: disable import feature on create dialog
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
Labels: bug

#186 fix: disable import feature on create dialog
  projects/portal/src/app/views/dialogs/wallets/ununifi/ununifi-create-wallet-form-dialog/ununifi-create-wallet-form-dialog.component.html
Labels: bug

#191 hotfix: chain id from ununifi test v2 to ununifi beta v1
  projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
Labels: bug

#192 hotfix: chain id from ununifi test v2 to ununifi beta v1
  projects/explorer/editions/ununifi/launch/ununifi/firebase-hosting/config.js
  projects/portal/editions/ununifi/launch/ununifi/firebase-hosting/config.js
Labels: bug
